#*******************************************************************************
#.appveyor.yml
#*******************************************************************************

#Purpose:
#AppVeyor is a hosted continuous integration service, that is, it allows running
#code directly from a repository and checking that the code acts as expected. 
#The purpose of the .appveyor.yml file is to give instructions to AppVeyor on
#how to do the work.
#Author:
#Cedric H. David, Jiayou Shi, and Wyte Krongapiradee, 2018-2018


#*******************************************************************************
#System specifications for AppVeyor
#*******************************************************************************
version: 1.0.{build}

build: false

image:
  - Visual Studio 2015
  

#*******************************************************************************
#Environment variables for different tests on multiple AppVeyor workers
#*******************************************************************************
environment:
  matrix:
    - TST_PUB_DWNL: 'tst_pub_dwnl_David_etal_201x_SER.sh'
      TST_PUB_REPR: 'tst_pub_repr_David_etal_201x_SER.sh'


#*******************************************************************************
#Before installing SHBAAM
#*******************************************************************************
install:
  - set PATH=C:\Miniconda-x64;C:\Miniconda-x64\Scripts;C:\cygwin64\bin;%PATH%
  - C:\cygwin64\setup-x86_64.exe --quiet-mode --no-shortcuts --upgrade-also --packages unzip


#*******************************************************************************
#Installing SHBAAM
#*******************************************************************************
build_script:
  - conda env create -f environment.yml
  - activate shbaam


#*******************************************************************************
#Testing SHBAAM
#*******************************************************************************
test_script:
  - cd tst
  - bash %TST_PUB_DWNL%
  - bash %TST_PUB_REPR%


#*******************************************************************************
#End
#*******************************************************************************
