#*******************************************************************************
#.travis.yml
#*******************************************************************************

#Purpose:
#Travis CI is a hosted continuous integration service, that is, it allows 
#running code directly from a repository and checking that the code acts as 
#expected. The purpose of the .travis.yml file is to give instructions to Travis 
#CI on how to do the work.
#Author:
#Cedric H. David, and Wyte Krongapiradee, 2017-2018


#*******************************************************************************
#Build Matrix
#*******************************************************************************
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: generic
      env: MINICONDA_INSTALLER=Miniconda2-latest-Linux-x86_64.sh
    - os: osx
      language: generic
      env: MINICONDA_INSTALLER=Miniconda2-latest-MacOSX-x86_64.sh


#*******************************************************************************
#Before installing SHBAAM
#*******************************************************************************
before_install:
  - wget https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install md5sha1sum; fi


#*******************************************************************************
#Installing SHBAAM
#*******************************************************************************
install:
  - conda env create -f environment.yml
  - source activate shbaam


#*******************************************************************************
#Testing SHBAAM
#*******************************************************************************
script:
  - cd tst
  - ./tst_pub_dwnl_David_etal_201x_SER.sh
  - ./tst_pub_repr_David_etal_201x_SER.sh


#*******************************************************************************
#End
#*******************************************************************************
