sudo: required

services:
  - docker

before_install:
  - docker build -t shbaam .

script:
  - cd tst
  - ./tst_pub_dwnl_David_etal_201x_SER.sh
  - cd ..
  - docker run
    --mount type=bind,source="$(pwd)"/input,target=/shbaam/input
    --mount type=bind,source="$(pwd)"/output,target=/shbaam/output
    shbaam
    /bin/bash -c "cd tst && ./tst_pub_repr_David_etal_201x_SER.sh"
