language: python

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      python: "2.7"
    - os: linux
      dist: trusty
      sudo: required
      python: "3.4"
    - os: linux
      dist: trusty
      sudo: required
      python: "3.5"
    - os: linux
      dist: trusty
      sudo: required
      python: "3.6"
    - os: osx
      language: generic
      env: PYTHON_VERSION=2.7.14
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.4.8
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.5.5
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.6.4

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt-get --version                                        ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update                                      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y $(grep -ve '^#' requirements.apt); fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew --version                                  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                                     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade pyenv                              ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which pyenv                                     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv --version                                 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then eval "$(pyenv init -)"                          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv versions                                  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv install -l                                ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv install $PYTHON_VERSION                   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv global $PYTHON_VERSION                    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv versions                                  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask uninstall oclint                      ; fi # see travis-ci/travis-ci#8826
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew reinstall $(grep -ve '^#' requirements.brw); fi
  - which python
  - python --version
  - which pip
  - pip --version

install:
  - pip install -r requirements.pip

script:
  - cd tst
  - travis_wait 120 ./tst_pub_dwnl_David_etal_201x_SER.sh
  - travis_wait 120 ./tst_pub_repr_David_etal_201x_SER.sh
